name:                ast-dfa
version:             0.1.0.0
github:              "karchx/ast-dfa"
license:             BSD-3-Clause
author:              "karchx"
maintainer:          ""
copyright:           "2026 karchx"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/karchx/ast-dfa#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  lexer-dfa-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ast-dfa

tests:
  lexer-dfa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ast-dfa
