{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Proto.Ast where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs
data BinOp
  = BinOpBIN_OP_UNSPECIFIED |
    BinOpBIN_OP_ADD |
    BinOpBIN_OP_SUB |
    BinOpBIN_OP_MUL |
    BinOpBIN_OP_DIV |
    BinOpBIN_OP_POW
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
instance (HsProtobuf.Named BinOp) where
  nameOf _ = Hs.fromString "BinOp"
instance (HsProtobuf.HasDefault BinOp)
instance (Hs.Bounded BinOp) where
  minBound = BinOpBIN_OP_UNSPECIFIED
  maxBound = BinOpBIN_OP_POW
instance (Hs.Ord BinOp) where
  compare x y
    = Hs.compare
        (HsProtobuf.fromProtoEnum x) (HsProtobuf.fromProtoEnum y)
instance (HsProtobuf.ProtoEnum BinOp) where
  toProtoEnumMay 0 = Hs.Just BinOpBIN_OP_UNSPECIFIED
  toProtoEnumMay 1 = Hs.Just BinOpBIN_OP_ADD
  toProtoEnumMay 2 = Hs.Just BinOpBIN_OP_SUB
  toProtoEnumMay 3 = Hs.Just BinOpBIN_OP_MUL
  toProtoEnumMay 4 = Hs.Just BinOpBIN_OP_DIV
  toProtoEnumMay 5 = Hs.Just BinOpBIN_OP_POW
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum BinOpBIN_OP_UNSPECIFIED = 0
  fromProtoEnum BinOpBIN_OP_ADD = 1
  fromProtoEnum BinOpBIN_OP_SUB = 2
  fromProtoEnum BinOpBIN_OP_MUL = 3
  fromProtoEnum BinOpBIN_OP_DIV = 4
  fromProtoEnum BinOpBIN_OP_POW = 5
instance (HsJSONPB.ToJSONPB BinOp) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
instance (HsJSONPB.FromJSONPB BinOp) where
  parseJSONPB (HsJSONPB.String "BIN_OP_UNSPECIFIED")
    = Hs.pure BinOpBIN_OP_UNSPECIFIED
  parseJSONPB (HsJSONPB.String "BIN_OP_ADD")
    = Hs.pure BinOpBIN_OP_ADD
  parseJSONPB (HsJSONPB.String "BIN_OP_SUB")
    = Hs.pure BinOpBIN_OP_SUB
  parseJSONPB (HsJSONPB.String "BIN_OP_MUL")
    = Hs.pure BinOpBIN_OP_MUL
  parseJSONPB (HsJSONPB.String "BIN_OP_DIV")
    = Hs.pure BinOpBIN_OP_DIV
  parseJSONPB (HsJSONPB.String "BIN_OP_POW")
    = Hs.pure BinOpBIN_OP_POW
  parseJSONPB v = HsJSONPB.typeMismatch "BinOp" v
instance (HsJSONPB.ToJSON BinOp) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON BinOp) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsProtobuf.Finite BinOp)
data Lambda
  = Lambda {lambdaParam :: Hs.Text,
            lambdaBody :: (Hs.Maybe Proto.Ast.Expr)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData Lambda)
instance (HsProtobuf.Named Lambda) where
  nameOf _ = Hs.fromString "Lambda"
instance (HsProtobuf.HasDefault Lambda)
instance (HsProtobuf.Message Lambda) where
  encodeMessage _ Lambda {lambdaParam, lambdaBody}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) lambdaParam))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce
               @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
              lambdaBody))
  decodeMessage _
    = Hs.pure Lambda
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "param") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Expr")))
         (HsProtobufAST.Single "body") [] ""]
instance (HsJSONPB.ToJSONPB Lambda) where
  toJSONPB (Lambda f1 f2)
    = HsJSONPB.object
        ["param" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "body"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                f2)]
  toEncodingPB (Lambda f1 f2)
    = HsJSONPB.pairs
        ["param" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
         "body"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                f2)]
instance (HsJSONPB.FromJSONPB Lambda) where
  parseJSONPB
    = HsJSONPB.withObject
        "Lambda"
        (\ obj
           -> Hs.pure Lambda
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "param"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
                     (obj .: "body")))
instance (HsJSONPB.ToJSON Lambda) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON Lambda) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsJSONPB.ToSchema Lambda) where
  declareNamedSchema _
    = do let declare_param = HsJSONPB.declareSchemaRef
         lambdaParam <- declare_param Proxy.Proxy
         let declare_body = HsJSONPB.declareSchemaRef
         lambdaBody <- declare_body Proxy.Proxy
         let _ = Hs.pure Lambda
                   <*>
                     ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                        (HsJSONPB.asProxy declare_param))
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
                        (HsJSONPB.asProxy declare_body))
         Hs.return
           HsJSONPB.NamedSchema
             {HsJSONPB._namedSchemaName = Hs.Just "Lambda",
              HsJSONPB._namedSchemaSchema = Hs.mempty
                                              {HsJSONPB._schemaParamSchema = Hs.mempty
                                                                               {HsJSONPB._paramSchemaType = Hs.Just
                                                                                                              HsJSONPB.SwaggerObject},
                                               HsJSONPB._schemaProperties = HsJSONPB.insOrdFromList
                                                                              [("param", 
                                                                                lambdaParam),
                                                                               ("body", 
                                                                                lambdaBody)]}}
data App
  = App {appFunc :: (Hs.Maybe Proto.Ast.Expr),
         appArg :: (Hs.Maybe Proto.Ast.Expr)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData App)
instance (HsProtobuf.Named App) where
  nameOf _ = Hs.fromString "App"
instance (HsProtobuf.HasDefault App)
instance (HsProtobuf.Message App) where
  encodeMessage _ App {appFunc, appArg}
    = Hs.mappend
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 1)
           ((Hs.coerce
               @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
              appFunc))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 2)
           ((Hs.coerce
               @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
              appArg))
  decodeMessage _
    = Hs.pure App
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Expr")))
         (HsProtobufAST.Single "func") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Expr")))
         (HsProtobufAST.Single "arg") [] ""]
instance (HsJSONPB.ToJSONPB App) where
  toJSONPB (App f1 f2)
    = HsJSONPB.object
        ["func"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                f1),
         "arg"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                f2)]
  toEncodingPB (App f1 f2)
    = HsJSONPB.pairs
        ["func"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                f1),
         "arg"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                f2)]
instance (HsJSONPB.FromJSONPB App) where
  parseJSONPB
    = HsJSONPB.withObject
        "App"
        (\ obj
           -> Hs.pure App
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
                     (obj .: "func"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
                     (obj .: "arg")))
instance (HsJSONPB.ToJSON App) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON App) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsJSONPB.ToSchema App) where
  declareNamedSchema _
    = do let declare_func = HsJSONPB.declareSchemaRef
         appFunc <- declare_func Proxy.Proxy
         let declare_arg = HsJSONPB.declareSchemaRef
         appArg <- declare_arg Proxy.Proxy
         let _ = Hs.pure App
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
                        (HsJSONPB.asProxy declare_func))
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
                        (HsJSONPB.asProxy declare_arg))
         Hs.return
           HsJSONPB.NamedSchema
             {HsJSONPB._namedSchemaName = Hs.Just "App",
              HsJSONPB._namedSchemaSchema = Hs.mempty
                                              {HsJSONPB._schemaParamSchema = Hs.mempty
                                                                               {HsJSONPB._paramSchemaType = Hs.Just
                                                                                                              HsJSONPB.SwaggerObject},
                                               HsJSONPB._schemaProperties = HsJSONPB.insOrdFromList
                                                                              [("func", appFunc),
                                                                               ("arg", appArg)]}}
data BinOpExpr
  = BinOpExpr {binOpExprOp :: (HsProtobuf.Enumerated Proto.Ast.BinOp),
               binOpExprLhs :: (Hs.Maybe Proto.Ast.Expr),
               binOpExprRhs :: (Hs.Maybe Proto.Ast.Expr)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData BinOpExpr)
instance (HsProtobuf.Named BinOpExpr) where
  nameOf _ = Hs.fromString "BinOpExpr"
instance (HsProtobuf.HasDefault BinOpExpr)
instance (HsProtobuf.Message BinOpExpr) where
  encodeMessage _ BinOpExpr {binOpExprOp, binOpExprLhs, binOpExprRhs}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1) binOpExprOp)
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce
                  @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                 binOpExprLhs)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce
               @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
              binOpExprRhs))
  decodeMessage _
    = Hs.pure BinOpExpr
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "BinOp")))
         (HsProtobufAST.Single "op") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Expr")))
         (HsProtobufAST.Single "lhs") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Expr")))
         (HsProtobufAST.Single "rhs") [] ""]
instance (HsJSONPB.ToJSONPB BinOpExpr) where
  toJSONPB (BinOpExpr f1 f2 f3)
    = HsJSONPB.object
        ["op" .= f1,
         "lhs"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                f2),
         "rhs"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                f3)]
  toEncodingPB (BinOpExpr f1 f2 f3)
    = HsJSONPB.pairs
        ["op" .= f1,
         "lhs"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                f2),
         "rhs"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Proto.Ast.Expr) @(HsProtobuf.Nested Proto.Ast.Expr))
                f3)]
instance (HsJSONPB.FromJSONPB BinOpExpr) where
  parseJSONPB
    = HsJSONPB.withObject
        "BinOpExpr"
        (\ obj
           -> Hs.pure BinOpExpr <*> obj .: "op"
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
                     (obj .: "lhs"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
                     (obj .: "rhs")))
instance (HsJSONPB.ToJSON BinOpExpr) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON BinOpExpr) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsJSONPB.ToSchema BinOpExpr) where
  declareNamedSchema _
    = do let declare_op = HsJSONPB.declareSchemaRef
         binOpExprOp <- declare_op Proxy.Proxy
         let declare_lhs = HsJSONPB.declareSchemaRef
         binOpExprLhs <- declare_lhs Proxy.Proxy
         let declare_rhs = HsJSONPB.declareSchemaRef
         binOpExprRhs <- declare_rhs Proxy.Proxy
         let _ = Hs.pure BinOpExpr <*> HsJSONPB.asProxy declare_op
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
                        (HsJSONPB.asProxy declare_lhs))
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.Nested Proto.Ast.Expr) @(Hs.Maybe Proto.Ast.Expr))
                        (HsJSONPB.asProxy declare_rhs))
         Hs.return
           HsJSONPB.NamedSchema
             {HsJSONPB._namedSchemaName = Hs.Just "BinOpExpr",
              HsJSONPB._namedSchemaSchema = Hs.mempty
                                              {HsJSONPB._schemaParamSchema = Hs.mempty
                                                                               {HsJSONPB._paramSchemaType = Hs.Just
                                                                                                              HsJSONPB.SwaggerObject},
                                               HsJSONPB._schemaProperties = HsJSONPB.insOrdFromList
                                                                              [("op", binOpExprOp),
                                                                               ("lhs", 
                                                                                binOpExprLhs),
                                                                               ("rhs", 
                                                                                binOpExprRhs)]}}
newtype Expr
  = Expr {exprExprKind :: (Hs.Maybe ExprExprKind)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData Expr)
instance (HsProtobuf.Named Expr) where
  nameOf _ = Hs.fromString "Expr"
instance (HsProtobuf.HasDefault Expr)
instance (HsProtobuf.Message Expr) where
  encodeMessage _ Expr {exprExprKind}
    = (case exprExprKind of
         Hs.Nothing -> Hs.mempty
         Hs.Just x
           -> case x of
                ExprExprKindLit y
                  -> HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 1) (HsProtobuf.ForceEmit y)
                ExprExprKindVar y
                  -> HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 2)
                       (HsProtobuf.ForceEmit
                          ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) y))
                ExprExprKindLam y
                  -> HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 3)
                       ((Hs.coerce
                           @(Hs.Maybe Proto.Ast.Lambda) @(HsProtobuf.Nested Proto.Ast.Lambda))
                          (Hs.Just y))
                ExprExprKindApp y
                  -> HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 4)
                       ((Hs.coerce
                           @(Hs.Maybe Proto.Ast.App) @(HsProtobuf.Nested Proto.Ast.App))
                          (Hs.Just y))
                ExprExprKindBinop y
                  -> HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 5)
                       ((Hs.coerce
                           @(Hs.Maybe Proto.Ast.BinOpExpr)
                           @(HsProtobuf.Nested Proto.Ast.BinOpExpr))
                          (Hs.Just y)))
  decodeMessage _
    = Hs.pure Expr
        <*>
          HsProtobuf.oneof
            Hs.Nothing
            [((HsProtobuf.FieldNumber 1), 
              Hs.pure (Hs.Just Hs.. ExprExprKindLit)
                <*> HsProtobuf.decodeMessageField),
             ((HsProtobuf.FieldNumber 2), 
              Hs.pure (Hs.Just Hs.. ExprExprKindVar)
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     HsProtobuf.decodeMessageField)),
             ((HsProtobuf.FieldNumber 3), 
              Hs.pure (Hs.fmap ExprExprKindLam)
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Proto.Ast.Lambda) @(Hs.Maybe Proto.Ast.Lambda))
                     HsProtobuf.decodeMessageField)),
             ((HsProtobuf.FieldNumber 4), 
              Hs.pure (Hs.fmap ExprExprKindApp)
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Proto.Ast.App) @(Hs.Maybe Proto.Ast.App))
                     HsProtobuf.decodeMessageField)),
             ((HsProtobuf.FieldNumber 5), 
              Hs.pure (Hs.fmap ExprExprKindBinop)
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Proto.Ast.BinOpExpr)
                      @(Hs.Maybe Proto.Ast.BinOpExpr))
                     HsProtobuf.decodeMessageField))]
  dotProto _ = []
instance (HsJSONPB.ToJSONPB Expr) where
  toJSONPB (Expr f1_or_f2_or_f3_or_f4_or_f5)
    = HsJSONPB.object
        [(let
            encodeExpr_kind
              = (case f1_or_f2_or_f3_or_f4_or_f5 of
                   Hs.Just (ExprExprKindLit f1) -> HsJSONPB.pair "lit" f1
                   Hs.Just (ExprExprKindVar f2)
                     -> HsJSONPB.pair
                          "var" ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
                   Hs.Just (ExprExprKindLam f3) -> HsJSONPB.pair "lam" f3
                   Hs.Just (ExprExprKindApp f4) -> HsJSONPB.pair "app" f4
                   Hs.Just (ExprExprKindBinop f5) -> HsJSONPB.pair "binop" f5
                   Hs.Nothing -> Hs.mempty)
          in
            (\ options
               -> if HsJSONPB.optEmitNamedOneof options then
                      ("expr_kind" .= HsJSONPB.objectOrNull [encodeExpr_kind] options)
                        options
                  else
                      encodeExpr_kind options))]
  toEncodingPB (Expr f1_or_f2_or_f3_or_f4_or_f5)
    = HsJSONPB.pairs
        [(let
            encodeExpr_kind
              = (case f1_or_f2_or_f3_or_f4_or_f5 of
                   Hs.Just (ExprExprKindLit f1) -> HsJSONPB.pair "lit" f1
                   Hs.Just (ExprExprKindVar f2)
                     -> HsJSONPB.pair
                          "var" ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
                   Hs.Just (ExprExprKindLam f3) -> HsJSONPB.pair "lam" f3
                   Hs.Just (ExprExprKindApp f4) -> HsJSONPB.pair "app" f4
                   Hs.Just (ExprExprKindBinop f5) -> HsJSONPB.pair "binop" f5
                   Hs.Nothing -> Hs.mempty)
          in
            (\ options
               -> if HsJSONPB.optEmitNamedOneof options then
                      ("expr_kind" .= HsJSONPB.pairsOrNull [encodeExpr_kind] options)
                        options
                  else
                      encodeExpr_kind options))]
instance (HsJSONPB.FromJSONPB Expr) where
  parseJSONPB
    = HsJSONPB.withObject
        "Expr"
        (\ obj
           -> Hs.pure Expr
                <*>
                  (let
                     parseExpr_kind parseObj
                       = Hs.msum
                           [Hs.Just Hs.. ExprExprKindLit
                              <$> HsJSONPB.parseField parseObj "lit",
                            Hs.Just Hs.. ExprExprKindVar
                              Hs.. (Hs.coerce @(HsProtobuf.String Hs.Text) @Hs.Text)
                              <$> HsJSONPB.parseField parseObj "var",
                            Hs.Just Hs.. ExprExprKindLam
                              <$> HsJSONPB.parseField parseObj "lam",
                            Hs.Just Hs.. ExprExprKindApp
                              <$> HsJSONPB.parseField parseObj "app",
                            Hs.Just Hs.. ExprExprKindBinop
                              <$> HsJSONPB.parseField parseObj "binop",
                            Hs.pure Hs.Nothing]
                   in
                     (obj .: "expr_kind"
                        Hs.>>= HsJSONPB.withObject "expr_kind" parseExpr_kind)
                       <|> (parseExpr_kind obj)))
instance (HsJSONPB.ToJSON Expr) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON Expr) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsJSONPB.ToSchema Expr) where
  declareNamedSchema _
    = do let declare_expr_kind = HsJSONPB.declareSchemaRef
         exprExprKind <- declare_expr_kind Proxy.Proxy
         let _ = Hs.pure Expr <*> HsJSONPB.asProxy declare_expr_kind
         Hs.return
           HsJSONPB.NamedSchema
             {HsJSONPB._namedSchemaName = Hs.Just "Expr",
              HsJSONPB._namedSchemaSchema = Hs.mempty
                                              {HsJSONPB._schemaParamSchema = Hs.mempty
                                                                               {HsJSONPB._paramSchemaType = Hs.Just
                                                                                                              HsJSONPB.SwaggerObject},
                                               HsJSONPB._schemaProperties = HsJSONPB.insOrdFromList
                                                                              [("expr_kind", 
                                                                                exprExprKind)]}}
data ExprExprKind
  = ExprExprKindLit Hs.Double |
    ExprExprKindVar Hs.Text |
    ExprExprKindLam Proto.Ast.Lambda |
    ExprExprKindApp Proto.Ast.App |
    ExprExprKindBinop Proto.Ast.BinOpExpr
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData ExprExprKind)
instance (HsProtobuf.Named ExprExprKind) where
  nameOf _ = Hs.fromString "ExprExprKind"
instance (HsJSONPB.ToSchema ExprExprKind) where
  declareNamedSchema _
    = do let declare_lit = HsJSONPB.declareSchemaRef
         exprExprKindLit <- declare_lit Proxy.Proxy
         let _ = Hs.pure ExprExprKindLit <*> HsJSONPB.asProxy declare_lit
         let declare_var = HsJSONPB.declareSchemaRef
         exprExprKindVar <- declare_var Proxy.Proxy
         let _ = Hs.pure ExprExprKindVar
                   <*>
                     ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                        (HsJSONPB.asProxy declare_var))
         let declare_lam = HsJSONPB.declareSchemaRef
         exprExprKindLam <- declare_lam Proxy.Proxy
         let _ = Hs.pure ExprExprKindLam <*> HsJSONPB.asProxy declare_lam
         let declare_app = HsJSONPB.declareSchemaRef
         exprExprKindApp <- declare_app Proxy.Proxy
         let _ = Hs.pure ExprExprKindApp <*> HsJSONPB.asProxy declare_app
         let declare_binop = HsJSONPB.declareSchemaRef
         exprExprKindBinop <- declare_binop Proxy.Proxy
         let _ = Hs.pure ExprExprKindBinop
                   <*> HsJSONPB.asProxy declare_binop
         Hs.return
           HsJSONPB.NamedSchema
             {HsJSONPB._namedSchemaName = Hs.Just "ExprExprKind",
              HsJSONPB._namedSchemaSchema = Hs.mempty
                                              {HsJSONPB._schemaParamSchema = Hs.mempty
                                                                               {HsJSONPB._paramSchemaType = Hs.Just
                                                                                                              HsJSONPB.SwaggerObject},
                                               HsJSONPB._schemaProperties = HsJSONPB.insOrdFromList
                                                                              [("lit", 
                                                                                exprExprKindLit),
                                                                               ("var", 
                                                                                exprExprKindVar),
                                                                               ("lam", 
                                                                                exprExprKindLam),
                                                                               ("app", 
                                                                                exprExprKindApp),
                                                                               ("binop", 
                                                                                exprExprKindBinop)],
                                               HsJSONPB._schemaMinProperties = Hs.Just 1,
                                               HsJSONPB._schemaMaxProperties = Hs.Just 1}}